# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """$all $fill $cmd_duration
$character"""

# Insert a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[→](bold red)'

[cmd_duration]
min_time=10
show_milliseconds = true
format = "[$duration](bright-dark)"

[fill]
symbol = ' '

[line_break]
disabled = true

[jobs]
disabled = true
